chore: Adds GCP Secret Manager trigger authentication docs
kedacore/keda-docs pull request #1203
Opened 2023-08-06 11:18 UTC by neelanjan00

_A description of what has been changed_
- Adds GCP Secret Manager trigger authentication docs

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

2024-01-12 06:16 UTC, wozniakjan reviewed
looks pretty good, just a couple of nits from my side, also the PR title should not be `chore` but `feat`, can you please change that?

2024-01-12 06:19 UTC, wozniakjan commented
@neelanjan00 regarding the failing jobs, I think you will need to adjust [`.htmltest`](https://github.com/kedacore/keda-docs/blob/main/.htmltest.yml) like in https://github.com/kedacore/keda-docs/commit/e03ee096b70db4300216c829c6d12c57cff81025

2024-01-12 09:40 UTC, zroubalik requested changes

2024-01-12 09:40 UTC, zroubalik commented on content/docs/2.12/authentication-providers/gcp-secret-manager.md
> ++++
+1

2024-01-12 09:40 UTC, zroubalik commented on content/docs/2.12/authentication-providers/gcp-secret-manager.md
> +  gcpCredentials:                                     # Optional.
please rename, https://github.com/kedacore/keda/pull/4864#pullrequestreview-1817786254

2024-01-12 09:41 UTC, zroubalik commented
@neelanjan00 please also add this page here to the list, to fix netlify issues: https://github.com/kedacore/keda-docs/blob/02d6f01ba1b8e1aa8b9ce36a18422eef50673bfa/.htmltest.yml#L8

2024-01-13 14:42 UTC, neelanjan00 commented
Thank you for the detailed reveiw, @wozniakjan @zroubalik. PTAL.

2024-01-15 07:42 UTC, wozniakjan approved these changes
lgtm

2024-01-15 10:18 UTC, zroubalik approved these changes

2024-01-15 13:54 UTC, merged