Introduce event filter in CloudEventSource
kedacore/keda-docs pull request #1301
Opened 2024-01-25 08:24 UTC by SpiritZhou

Introduce event filter in CloudEventSource

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #
https://github.com/kedacore/keda/pull/5424

2024-01-27 12:45 UTC, tomkerkhove requested changes
I'm not sure I get this PR, are we missing changes for filtering, @SpiritZhou ?

2024-01-27 12:45 UTC, tomkerkhove commented on content/docs/2.14/operate/events.md
> +[+++
This is probably not intentional?
```suggestion
+++
```

2024-01-27 12:45 UTC, tomkerkhove commented on content/docs/2.14/operate/events.md
> +KEDA emits the following \[Kubernetes Events\](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#event-v1-core):
```suggestion
KEDA emits the following [Kubernetes Events](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#event-v1-core):
```

2024-01-27 12:45 UTC, tomkerkhove commented on content/docs/2.14/operate/events.md
> +- \[HTTP endpoint\](#http-endpoint).
```suggestion
- [HTTP endpoint](#http-endpoint).
```

2024-01-27 12:45 UTC, tomkerkhove commented on content/docs/2.14/operate/events.md
> +| `keda.scaledobject.failed.v1`             | If the check validation for a ScaledObject fails |      ](../../2.13/operate/events.md)
Is this intentional?
```suggestion
| `keda.scaledobject.failed.v1`             | If the check validation for a ScaledObject fails |     
```

2024-02-18 06:22 UTC, SpiritZhou commented
> I'm not sure I get this PR, are we missing changes for filtering, @SpiritZhou ?

Sorry, I might have messed up when merging main branch.

2024-02-20 12:47 UTC, tomkerkhove commented on content/docs/2.14/operate/events.md
> +        - keda.scaledobject.ready.v1
Nit - I think the formatting might be off?

```suggestion
  destination:
    http:
      uri: http://foo.bar
  eventSubscription: #Optional. Submit included/excluded event types will filter events when emitting events. 
    includedEventTypes: #Optional. Only events in this section will be emitted.
    - keda.scaledobject.failed.v1
    excludedEventTypes: #Optional. Events in this section will not be emitted.       
    - keda.scaledobject.ready.v1
```

2024-03-23 13:42 UTC, tomkerkhove approved these changes
LGTM, thanks! Waiting for feature to merge

2024-03-31 17:30 UTC, JorTurFer approved these changes

2024-04-10 21:22 UTC, merged