Feat: Copy to Clipboard for FAQ
kedacore/keda-docs pull request #1303
Opened 2024-02-02 03:05 UTC by thisisobate

Fixes #1274 1274

2024-02-06 06:53 UTC, tomkerkhove requested changes
Thanks a ton!

Just a few suggestions:


- Can we make the button less explicit? It's pretty invasive but it might be me, @zroubalik/@JorTurFer ?

![image](https://github.com/kedacore/keda-docs/assets/4345663/3c76a073-81c4-4cd7-90f8-58e3f74ea9a6)

- When copying a link and going to the URL, the item does not expand so I still have to look for it, can we auto-expand them?

- Can we do the same for troubleshooting?
![image](https://github.com/kedacore/keda-docs/assets/4345663/ddcb8b76-25b3-4aa7-b68d-23d88bd3e939)

2024-02-06 07:36 UTC, JorTurFer commented
I agree with all your points 😄

2024-02-06 11:50 UTC, zroubalik approved these changes
Agree with @tomkerkhove

2024-02-07 13:21 UTC, tomkerkhove commented
> @tomkerkhove I suggest we do the troubleshooting part in a separate PR.

Sounds good!

2024-02-07 13:22 UTC, tomkerkhove commented
The expanding is great! However, if I wouldn't now there was a button I would not see it since it requires a hover:
![image](https://github.com/kedacore/keda-docs/assets/4345663/3bfdbd52-f65c-4133-ab4f-2f34ee3af407)

Can we maybe just get rid of the full blue background and always show a subtle icon?

2024-02-07 14:02 UTC, thisisobate commented
@tomkerkhove How about this?

<img width="1704" alt="Screenshot 2024-02-07 at 15 01 57" src="https://github.com/kedacore/keda-docs/assets/29557702/767962ad-0761-4769-9127-27382c27eac5">

2024-02-07 14:10 UTC, zroubalik reviewed
This icon looks better, though it might be just me but the icon gives me impression that I am about to copy some piece of text or code, not a link. Do we have an icon like this?
<img width="24" alt="Screenshot 2024-02-07 at 15 10 26" src="https://github.com/kedacore/keda-docs/assets/726523/5e862d57-4353-4421-ba0f-fae3d8538ab9">

2024-02-07 14:41 UTC, thisisobate commented
@zroubalik Yes, we do.
I agree with you on the icons.
Will substitute the **clone** icon with the **link** icon.

2024-02-08 12:35 UTC, tomkerkhove commented
Works like a charm, thanks! However, it no longer auto-expands which it used to do though :(

2024-02-08 13:48 UTC, thisisobate commented
@tomkerkhove Actually, it does expand. It looks like you tried loading the FAQ link in the same tab. 
To test appropriately, copy the link and load it in a separate tab. That should work.

2024-02-09 13:42 UTC, tomkerkhove commented
Hm, why would that not work? It's not a blocker but curious though

2024-02-09 13:42 UTC, tomkerkhove approved these changes

2024-02-09 14:13 UTC, thisisobate commented
> Hm, why would that not work? It's not a blocker but curious though

So here's a bit of an explanation of why it won't work:, 
By default, pages are cached when loaded in the browser tab. Now, when you try to navigate to an internal link (FAQ link) in this case, it won't cause a reload or rerender because it's an internal link; thus the reason why you can't see a change when you load the link in the same tab. 

Hope that helps.

2024-02-09 15:00 UTC, merged

2024-02-09 15:00 UTC, tomkerkhove commented
Thanks!