docs(scalers): Add documentation for an additional configuration that…
kedacore/keda-docs pull request #1305
Opened 2024-02-06 05:51 UTC by ArunYogesh

Update Kafka scaler to document Kerberos Service Name configuration

_Provide a description of what has been changed_

### Checklist

- [ x] Commits are signed with Developer Certificate of Origin (DCO)

Relates to [#5474](https://github.com/kedacore/keda/issues/5474)
Part of the [core PR](https://github.com/kedacore/keda/pull/5483)

2024-02-06 23:09 UTC, JorTurFer approved these changes

2024-02-12 12:41 UTC, zroubalik requested changes

2024-02-12 12:41 UTC, zroubalik commented on content/docs/2.14/scalers/apache-kafka.md
> +- `serviceName` - Kerberos service name. (Optional takes default value of `kafka` if not provided)
```suggestion
- `kerberosServiceName` - Kerberos service name. (Optional takes default value of `kafka` if not provided)
```

2024-02-12 12:41 UTC, zroubalik commented on content/docs/2.14/scalers/apache-kafka.md
> +- `serviceName` - Kerberos service name. (Optional takes default value of `kafka` if not provided)
To make it explicit that this setting is about kerberos

2024-03-10 18:48 UTC, JorTurFer approved these changes

2024-03-10 23:26 UTC, merged