feature[v2]: adding documentation regarding authentication in metric scalers
kedacore/keda-docs pull request #260
Opened 2020-09-15 06:19 UTC by aman-bansal

This is related to #1137 . Authentication methods for metric scaler api has been added. Currently supported authModes are API key-based authentication, Basic Authentication and TLS authentication.

Signed-off-by: aman-bansal <bansalaman2905@gmail.com>

2020-09-15 06:53 UTC, tomkerkhove commented
I'll review it ASAP but can you update the trigger spec as well please?
https://github.com/kedacore/keda-docs/pull/260/files#diff-2079ef1d5bc7dbe2c2470f43d8749c87R18

2020-09-16 15:47 UTC, aman-bansal commented
> I'll review it ASAP but can you update the trigger spec as well please?
> https://github.com/kedacore/keda-docs/pull/260/files#diff-2079ef1d5bc7dbe2c2470f43d8749c87R18

Hey didn't get this part? Did it miss something in the documentation?

2020-09-17 08:03 UTC, tomkerkhove commented
I've missed the implementation side of things but presume we do not only support authentication parameters but define it in https://github.com/kedacore/keda-docs/pull/260/files#diff-2079ef1d5bc7dbe2c2470f43d8749c87R19-R24 as well by using `FromEnv` for secrets and literal values such as `authMode`?

2020-09-17 08:22 UTC, tomkerkhove requested changes

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +Metrics Scaler API supported three types of authentication. API Key based authentication, basic authentication and TLS
```suggestion
Metrics Scaler API supported three types of authentication - API Key based authentication, basic authentication and TLS 
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +authentication. You can use `TriggerAuthentication` CRD to configure the authentication by providing `authMode` along
```suggestion
authentication.

You can use `TriggerAuthentication` CRD to configure the authentication by providing `authMode` along 
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +- `authMode`: It must be set to `apiKeyAuth` in case of Basic Authentication.
Nit - No need to use `Auth` suffix
```suggestion
- `authMode`: It must be set to `apiKey` in case of API key authentication.
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +- `authMode`: It must be set to `basicAuth` in case of Basic Authentication.
Same nit, but optional
```suggestion
- `authMode`: It must be set to `basic` in case of basic authentication.
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +- `authMode`: It must be set to `tlsAuth` in case of TLS Authentication.
Same nit, but optional

```suggestion
- `authMode`: It must be set to `tls` in case of TLS authentication.
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +For metric scaler with API Key based authentication,
```suggestion
Here is an example of a metric scaler with API Key based authentication:
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +
```suggestion
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +
```suggestion
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +
```suggestion
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +
```suggestion
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +
```suggestion
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +
```suggestion
```

2020-09-17 08:22 UTC, tomkerkhove commented on content/docs/2.0/scalers/metrics-api.md
> +
```suggestion
```

2020-09-17 08:23 UTC, tomkerkhove commented
Just as an example @aman-bansal:
We currently have this sample:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keda-metric-api-secret
  namespace: default
data:
  authMode: "apiKeyAuth"
  apiKey: "APIKEY" 
  method: "query"
  keyParamName: "QUERY_KEY"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-metric-api-creds
  namespace: default
spec:
  secretTargetRef:
    - parameter: authMode
      name: keda-metric-api-secret
      key: authMode
    - parameter: apiKey
      name: keda-metric-api-secret
      key: apiKey
    - parameter: method
      name: keda-metric-api-secret
      key: method
    - parameter: keyParamName
      name: keda-metric-api-secret
      key: keyParamName
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject
  namespace: keda
  labels:
    deploymentName: dummy
spec:
  maxReplicaCount: 12
  scaleTargetRef:
    name: dummy
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "7"
        url: "http://api:3232/components/stats"
        valueLocation: 'components.worker.tasks'
      authenticationRef:
        name: keda-metric-api-creds
```

But I'd expect to be able to define it like this:
```yaml

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject
  namespace: keda
  labels:
    deploymentName: dummy
spec:
  maxReplicaCount: 12
  scaleTargetRef:
    name: dummy
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "7"
        url: "http://api:3232/components/stats"
        valueLocation: 'components.worker.tasks'
        authMode: apiKeyAuth
        method: query
        keyParamName: QUERY_KEY
      authenticationRef:
        name: keda-metric-api-creds
```

2020-09-23 07:09 UTC, aman-bansal commented
Guys I am on leave for two weeks. Will be back next week. Will continue with this after that :)

2020-10-09 08:17 UTC, zroubalik commented
@aman-bansal could you please update and rebase this PR? thanks!

2020-10-12 16:29 UTC, aman-bansal commented
> ```yaml
> metadata:
>         targetValue: "7"
>         url: "http://api:3232/components/stats"
>         valueLocation: 'components.worker.tasks'
>         authMode: apiKeyAuth
>         method: query
>         keyParamName: QUERY_KEY
> ```

Okay, so what I understand from this is only critical security params like username or password should be passed via auth params. Other parameters should use basic metadata map.

@tomkerkhove is my understanding correct?

2020-10-13 05:50 UTC, tomkerkhove commented
> > ```yaml
> > metadata:
> >         targetValue: "7"
> >         url: "http://api:3232/components/stats"
> >         valueLocation: 'components.worker.tasks'
> >         authMode: apiKeyAuth
> >         method: query
> >         keyParamName: QUERY_KEY
> > ```
> 
> Okay, so what I understand from this is only critical security params like username or password should be passed via auth params. Other parameters should use basic metadata map.
> 
> @tomkerkhove is my understanding correct?

Yes, TriggerAuthentication is only for secrets

2020-10-15 07:11 UTC, aman-bansal commented
@tomkerkhove I have updated the docs. Now, these changes require an update of the scaler itself. Here is the PR for that https://github.com/kedacore/keda/pull/1258

2020-10-15 09:02 UTC, zroubalik commented
> @tomkerkhove I have updated the docs. Now, these changes require an update of the scaler itself. Here is the PR for that [kedacore/keda#1258](https://github.com/kedacore/keda/pull/1258)

The PR is merged, I'll keep this PR for Tom's review.

Thanks @aman-bansal !

2020-10-15 12:48 UTC, tomkerkhove approved these changes
LGTM, thanks!

2020-10-15 12:48 UTC, merged