Provide version for 2.0 installation with Helm
kedacore/keda-docs pull request #266
Opened 2020-09-22 11:09 UTC by tomkerkhove

Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

2020-09-22 11:38 UTC, zroubalik commented
@tomkerkhove LGTM, but I think we should fix this one first: https://github.com/kedacore/charts/issues/71
And release Beta1.2 then 🤷‍♂️

2020-09-23 14:20 UTC, zroubalik requested changes

2020-09-23 14:20 UTC, zroubalik commented on content/docs/2.0/deploy.md
> +    helm install keda kedacore/keda --version 2.0.0-beta1.1 --namespace keda
```suggestion
    helm install keda kedacore/keda --version 2.0.0-beta1.2 --namespace keda
```

2020-09-24 00:51 UTC, ahmelsayed approved these changes

2020-09-24 07:40 UTC, merged