update postgres scaler docs with metricName
kedacore/keda-docs pull request #313
Opened 2020-11-25 23:40 UTC by ycabrer

Signed-off-by: ycabrer <43866176+ycabrer@users.noreply.github.com>

2020-11-26 09:48 UTC, zroubalik requested changes

2020-11-26 09:48 UTC, zroubalik commented on content/docs/1.4/scalers/postgresql.md
> +- `metricName` - an optional name to assign to the metric
Could you please add more information on the metricName and its usage. ie. that KEDA will generate the metric name from xyz values and this setting could be used to override. And that this is important only if there are multiple postresql scalers in one ScaledObject. Thanks

2020-11-27 14:50 UTC, zroubalik commented
could you please target this against 2.1 and not 1.4, eg `content/docs/2.1/scalers/`

2020-11-30 19:22 UTC, ycabrer commented
Whoops, that would help. Yes.

2020-11-30 19:45 UTC, ycabrer commented
@zroubalik I hope that's better. Let me know if it needs anything else!

Thank you!

2020-12-01 10:02 UTC, zroubalik reviewed
Looking good, minor nit only!

2020-12-01 10:02 UTC, zroubalik commented on content/docs/2.1/scalers/postgresql.md
> +- `metricName` - an optional name to assign to the metric. If not set keda will generate a name based on either the connection string if set or the db name. If using more than one trigger it is requi
```suggestion
- `metricName` - an optional name to assign to the metric. If not set KEDA will generate a name based on either the connection string if set or the db name. If using more than one trigger it is required that all metricNames be unique.
```

2020-12-02 04:27 UTC, ycabrer commented on content/docs/2.1/scalers/postgresql.md
> +- `metricName` - an optional name to assign to the metric. If not set keda will generate a name based on either the connection string if set or the db name. If using more than one trigger it is requi
I'll get it updated now

2020-12-02 06:31 UTC, tomkerkhove approved these changes

2020-12-02 06:31 UTC, merged