Add events.md
kedacore/keda-docs pull request #361
Opened 2021-01-29 20:11 UTC by ahmelsayed

Signed-off-by: Ahmed ElSayed <ahmels@microsoft.com>

2021-01-30 09:00 UTC, tomkerkhove requested changes
Thanks for these docs!

I've added a remark on https://github.com/kedacore/keda/pull/1523#issuecomment-770180510 so I'll wait with reviewing until we decided on that.

Would you mind moving these docs from v2.0 to v2.2, please, since that's the version where this will be introduced.

2021-02-08 06:23 UTC, tomkerkhove reviewed
This might be a stretch, but do you have raw payloads for these events as examples?

2021-02-08 06:23 UTC, tomkerkhove commented on content/docs/2.0/operate/_index.md
> +- Kubernetes Events ([link](./events))
Can you move this to v2.2 please?

2021-02-08 06:23 UTC, tomkerkhove commented on content/docs/2.2/operate/events.md
> +KEDA emits the following [Kubernetes Events](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#event-v1-core)
```suggestion
KEDA emits the following [Kubernetes Events](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#event-v1-core):

```

2021-02-12 20:34 UTC, ahmelsayed commented on content/docs/2.0/operate/_index.md
> +- Kubernetes Events ([link](./events))
oops, sorry forgot about this one.

2021-02-15 08:29 UTC, tomkerkhove approved these changes
LGTM, thanks a ton @ahmelsayed!

2021-02-15 08:29 UTC, merged