add allowIdleConsumers documentation
kedacore/keda-docs pull request #407
Opened 2021-03-25 17:39 UTC by lionelvillard

Documentation for this proposed new feature: https://github.com/kedacore/keda/pull/1684

2021-03-25 18:47 UTC, tomkerkhove approved these changes

2021-03-25 18:48 UTC, tomkerkhove commented
Waiting for feature PR to be merged but LGTM, thanks!

2021-03-26 07:59 UTC, zroubalik requested changes

2021-03-26 07:59 UTC, zroubalik commented on content/docs/2.3/scalers/apache-kafka.md
> +partitions on a topic, allowing for idle consumers.
```suggestion
- `allowIdleConsumers` - Optional. When set to `true`, the number of replicas can exceed the number of
partitions on a topic, allowing for idle consumers. (default: `false`)
```

2021-03-26 14:54 UTC, zroubalik approved these changes
LGTM

2021-03-26 14:55 UTC, merged