docs: Provide consistent docs for trigger authentication
kedacore/keda-docs pull request #498
Opened 2021-08-02 13:14 UTC by tomkerkhove

Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

Provide consistent docs for trigger authentication across all scalers.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

2021-11-03 14:26 UTC, tomkerkhove commented
@JorTurFer Would you mind taking a look as well?

2021-11-03 15:56 UTC, JorTurFer requested changes
Nice job! only small nits

2021-11-03 15:56 UTC, JorTurFer commented on content/docs/2.0/scalers/redis-streams.md
> +- `password` - Redis password to authenticate with
```suggestion
- `password` - Redis password to authenticate with.
```

2021-11-03 15:56 UTC, JorTurFer commented on content/docs/2.1/scalers/redis-cluster-streams.md
> +- `password` - Redis password to authenticate with
```suggestion
- `password` - Redis password to authenticate with.
```

2021-11-03 15:56 UTC, JorTurFer commented on content/docs/2.1/scalers/redis-streams.md
> +- `password` - Redis password to authenticate with
```suggestion
- `password` - Redis password to authenticate with.
```

2021-11-03 15:56 UTC, JorTurFer commented on content/docs/2.2/scalers/redis-cluster-streams.md
> +- `password` - Redis password to authenticate with
```suggestion
- `password` - Redis password to authenticate with.
```

2021-11-03 15:56 UTC, JorTurFer commented on content/docs/2.2/scalers/redis-streams.md
> +- `password` - Redis password to authenticate with
```suggestion
- `password` - Redis password to authenticate with.
```

2021-11-03 15:56 UTC, JorTurFer commented on content/docs/2.3/scalers/redis-cluster-streams.md
> +- `password` - Redis password to authenticate with
```suggestion
- `password` - Redis password to authenticate with.
```

2021-11-03 15:56 UTC, JorTurFer commented on content/docs/2.3/scalers/redis-streams.md
> +- `password` - Redis password to authenticate with
```suggestion
- `password` - Redis password to authenticate with.
```

2021-11-03 15:56 UTC, JorTurFer commented on content/docs/2.4/scalers/redis-cluster-streams.md
> +- `password` - Redis password to authenticate with
```suggestion
- `password` - Redis password to authenticate with.
```

2021-11-03 15:56 UTC, JorTurFer commented on content/docs/2.4/scalers/redis-streams.md
> +- `password` - Redis password to authenticate with
```suggestion
- `password` - Redis password to authenticate with.
```

2021-11-03 15:56 UTC, JorTurFer commented on content/docs/2.4/scalers/solace-pub-sub.md
> +- `password` The password to use to connect to the Solace PubSub+ Event Broker's SEMP endpoint.
```suggestion
- `username` - The username to use to connect to the Solace PubSub+ Event Broker's SEMP endpoint.
- `password` - The password to use to connect to the Solace PubSub+ Event Broker's SEMP endpoint.
```

2021-11-04 07:14 UTC, JorTurFer approved these changes
LGTM!

2021-11-04 07:16 UTC, merged