TriggerAuthentication/Vault: add support for vault namespace
kedacore/keda-docs pull request #522
Opened 2021-09-01 15:52 UTC by chapurlatn

Signed-off-by: Nicolas Chapurlat <nc@coorganix.com>

### Changes

Related to keda PR [https://github.com/kedacore/keda/pull/2085](https://github.com/kedacore/keda/pull/2085)
- Just add the optional Vault namespace in the Vault TriggerAuthentication example.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

2021-09-02 06:53 UTC, tomkerkhove requested changes
Thank you! It will just need a bit more changes.

2021-09-02 06:53 UTC, tomkerkhove commented on content/docs/1.5/concepts/authentication.md
> +    namespace: {hashicorp-vault-namespace} # Optional. Useful for Vault Enterprise
Next to that, can you update the "Hashicorp Vault secret(s)" section below as well please?

2021-09-02 13:31 UTC, chapurlatn commented on content/docs/1.5/concepts/authentication.md
> +    namespace: {hashicorp-vault-namespace} # Optional. Useful for Vault Enterprise
k, I'll do that (sorry for the bad version..)

2021-09-02 14:20 UTC, chapurlatn commented on content/docs/1.5/concepts/authentication.md
> +    namespace: {hashicorp-vault-namespace} # Optional. Useful for Vault Enterprise
done, with a lightweight comment about `namespace` in description

2021-09-02 14:22 UTC, tomkerkhove approved these changes
Thank you!

2021-09-10 07:36 UTC, zroubalik approved these changes

2021-09-10 07:38 UTC, merged