update aws cloudwatch scaler doc
kedacore/keda-docs pull request #568
Opened 2021-11-03 18:40 UTC by fivesheep

Signed-off-by: Xiayang Wu <xwu@rippling.com>

_Provide a description of what has been changed_

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

update `content/docs/2.4/scalers/aws-cloudwatch.md` and `content/docs/2.5/scalers/aws-cloudwatch.md` for the two new parameters `metricUnit` and `metricEndTimeOffset` that are introduced by https://github.com/kedacore/keda/pull/2243

2021-11-03 18:49 UTC, JorTurFer requested changes
Thanks for your contribution!!
Could you undo the changes in v2.4? The changes that you have done will be merged with main branch and released in the version 2.5. Since v2.4 was released some time ago, it has no sense update it :)

2021-11-03 20:22 UTC, JorTurFer approved these changes
LGTM!

2021-11-04 06:41 UTC, tomkerkhove requested changes

2021-11-04 06:41 UTC, tomkerkhove commented on content/docs/2.5/scalers/aws-cloudwatch.md
> +- `metricCollectionTime` - How long in the past (seconds) should the scaler check AWS Cloudwatch. Used to define **StartTime** ([official documentation](https://docs.aws.amazon.com/AmazonCloudWatch/l
Can you also add `metricUnit` here please?

2021-11-04 15:59 UTC, tomkerkhove approved these changes

2021-11-04 16:00 UTC, tomkerkhove commented
Thank you! Waiting for the reature to merge so we can close this.

2021-11-04 16:07 UTC, merged