Welcome GittiGidiyor, a new KEDA user!
kedacore/keda-docs pull request #588
Opened 2021-11-21 13:42 UTC by nilayasiktoprak

Signed-off-by: nilayasiktoprak <nilayasiktoprak@gmail.com>

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO)

2021-11-21 17:44 UTC, JorTurFer requested changes
First of all: WELCOME!!!! 🥳 
Only small nit, 
could you order it alphabetically? This should be between fission and hmcts :)

2021-11-21 18:01 UTC, nilayasiktoprak commented
Oh yes, i only paid attention to the first letters :)

2021-11-21 18:24 UTC, JorTurFer approved these changes

2021-11-22 08:13 UTC, tomkerkhove approved these changes
Thank you! 🎉🎉

2021-11-22 08:13 UTC, merged