Add blog re post of how Zapier uses KEDA
kedacore/keda-docs pull request #687
Opened 2022-03-04 12:01 UTC by rtnpro

This is a repost of the original blog post published in CNCF blog here: https://www.cncf.io/blog/2022/01/21/keda-at-zapier/

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

2022-03-04 12:10 UTC, JorTurFer approved these changes

2022-03-04 12:13 UTC, tomkerkhove requested changes

2022-03-04 12:13 UTC, tomkerkhove commented on content/blog/2022-03-07-how-zapier-uses-keda.md
> +
Might be good to add a paragraph here how you are using KEDA to lure people to read more.

For example, scale on RabbitMQ queue depth and use Prometheus metrics for operations

2022-03-09 13:39 UTC, rtnpro commented on content/blog/2022-03-10-how-zapier-uses-keda.md
> +
@tomkerkhove Does this look good?

2022-03-09 13:54 UTC, tomkerkhove approved these changes
LGTM, thanks a ton @rtnpro!

2022-03-09 13:54 UTC, merged