doc(newrelic): add doc for new relic account and region from auth config
kedacore/keda-docs pull request #744
Opened 2022-04-11 17:43 UTC by pragmaticivan

Signed-off-by: Ivan Santos <301291+pragmaticivan@users.noreply.github.com>

Adds documentation changes to include `account` and `region` via Auth config.
### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #2883

2022-04-11 21:27 UTC, JorTurFer requested changes
Thanks for this improvement.
2 comments inline

2022-04-11 21:27 UTC, JorTurFer commented on content/docs/2.7/scalers/new-relic.md
> +  secretTargetRef:
`secretTargetRef` is an array of objects with the 3 keys, duplicating the `secretTargetRef` is incorrect. Could you update this?

2022-04-11 21:27 UTC, JorTurFer commented on content/docs/2.7/scalers/new-relic.md
> +  secretTargetRef:
Same as above

2022-04-12 01:23 UTC, pragmaticivan commented
@JorTurFer Fixed, thanks!

2022-04-12 06:39 UTC, JorTurFer approved these changes
LGTM!
Thanks for this improvemente ❤️

2022-04-12 08:07 UTC, zroubalik approved these changes

2022-04-12 08:07 UTC, merged