Add doc for new dapr checkpoint strategy for Azure Event Hubs scalar
kedacore/keda-docs pull request #775
Opened 2022-06-07 18:23 UTC by brainslush

Adds documentation for the new dapr checkpoint strategy for Azure Event Hubs scalar. Explains the new option `dapr`  for the `checkpointStrategy` field. Removes dapr reference from `goSdk` checkpoint strategy documentation. 

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #

2022-06-08 12:12 UTC, tomkerkhove requested changes

2022-06-08 12:12 UTC, tomkerkhove commented on content/docs/2.8/scalers/azure-event-hub.md
> +    - `dapr` - A dapr specific checkpoint strategy based on the `goSdk` checkpointing implementation but using the dapr naming scheme.
I think the current information is an implementation detail for end-users, what about simply this?
```suggestion
    - `dapr` - Used for Dapr applications using Azure Event Grid.
```

2022-06-12 21:13 UTC, brainslush reviewed
shortened as requested

2022-06-13 07:25 UTC, tomkerkhove approved these changes
LGTM, thanks!

2022-12-09 11:57 UTC, tomkerkhove commented
Done in https://github.com/kedacore/keda-docs/pull/996

2022-12-09 11:57 UTC, closed without merging