updating redirects, removing unreachable files
kedacore/keda-docs pull request #816
Opened 2022-07-13 22:10 UTC by nate-double-u

Moving redirects from `static/_redirects` to `layouts/index.redirects`
removing `content/troubleshooting` folder as it is not accessible
adding npm command `netlify-serve` to allow for testing redirects locally.

fixes #668

2022-07-13 22:39 UTC, nate-double-u commented
deploy preview redirects tests:
* [x] https://deploy-preview-816--keda.netlify.app/docs -> https://deploy-preview-816--keda.netlify.app/docs/2.7/
* [x] https://deploy-preview-816--keda.netlify.app/docs/latest -> https://deploy-preview-816--keda.netlify.app/docs/2.7/
* [x] https://deploy-preview-816--keda.netlify.app/concepts -> https://deploy-preview-816--keda.netlify.app/docs/2.7/concepts/
* [ ] https://deploy-preview-816--keda.netlify.app/concepts/overview -> https://deploy-preview-816--keda.netlify.app/docs/2.7/concepts/overview
* [x] https://deploy-preview-816--keda.netlify.app/deploy -> https://deploy-preview-816--keda.netlify.app/docs/2.7/deploy/
* [x] https://deploy-preview-816--keda.netlify.app/faq -> https://deploy-preview-816--keda.netlify.app/docs/2.7/faq/
* [x] https://deploy-preview-816--keda.netlify.app/scalers -> https://deploy-preview-816--keda.netlify.app/docs/2.7/scalers
* [x] https://deploy-preview-816--keda.netlify.app/troubleshooting -> https://deploy-preview-816--keda.netlify.app/docs/2.7/troubleshooting/
* [x] https://deploy-preview-816--keda.netlify.app/operate -> https://deploy-preview-816--keda.netlify.app/docs/2.7/operate/
* [x] https://deploy-preview-816--keda.netlify.app/deploy -> https://deploy-preview-816--keda.netlify.app/docs/2.7/deploy/

2022-07-13 22:48 UTC, nate-double-u commented
Instead of removing `content/troubleshooting` should it be moved?

2022-07-13 22:50 UTC, nate-double-u commented
/cc @thisisobate @chalin

2022-07-14 07:16 UTC, JorTurFer commented
> Instead of removing `content/troubleshooting` should it be moved?

I think that the content could be useful yet. GKE could be outdated, but the others apply now. I'd not remove them

2022-07-14 07:45 UTC, tomkerkhove commented
> Instead of removing `content/troubleshooting` should it be moved?

It should be moved indeed because now that it is removed, all entries on https://deploy-preview-816--keda.netlify.app/docs/2.7/troubleshooting/ are gone.

As reference, this is how it is in the production version: https://keda.sh/docs/2.7/troubleshooting/

The files there are being included as sections.

2022-07-14 07:45 UTC, tomkerkhove requested changes
Please bring back the troubleshooting files and/or move them.

See https://github.com/kedacore/keda-docs/pull/816#issuecomment-1184110714

2025-05-30 20:02 UTC, nate-double-u commented
Closing as stale (and the issue this was based on appears to be closed).

2025-05-30 20:02 UTC, closed without merging