Documentation for Datadog Multi-Query Support
kedacore/keda-docs pull request #885
Opened 2022-08-10 11:41 UTC by dgibbard-cisco

Signed-off-by: Darren Gibbard <dgibbard@cisco.com>

Documentation to support the Datadog Multi-Query Support added in https://github.com/kedacore/keda/pull/3550

### Checklist

- [ ] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #3423

2022-08-10 11:43 UTC, dgibbard-cisco commented
Would be good to get @arapulido 's eyes on this too if available, as the main code creator :)

2022-08-10 11:55 UTC, tomkerkhove requested changes
LGTM, a few nits

2022-08-10 11:55 UTC, tomkerkhove commented on content/docs/2.9/scalers/datadog.md
> +To reduce issues with API Rate Limiting from Datadog, it is possible to send a single query, which contains multiple queries, comma-seperated.
```suggestion
To reduce issues with API rate limiting from Datadog, it is possible to send a single query, which contains multiple queries, comma-seperated.
```

2022-08-10 11:55 UTC, tomkerkhove commented on content/docs/2.9/scalers/datadog.md
> +      queryAggregator: "max"
Can you add this to the parameter list above please?

2022-08-10 12:04 UTC, dgibbard-cisco commented
> LGTM, a few nits

Thanks for the review! Have made the changes as suggested 👍

2022-08-10 12:29 UTC, tomkerkhove approved these changes

2022-08-11 08:30 UTC, arapulido requested changes
Small suggestion. Other than that, LGTM

2022-08-11 10:33 UTC, dgibbard-cisco commented on content/docs/2.9/scalers/datadog.md
> +When doing this, the results from each query are aggregated based on the `queryAggregator` value (eg: `max` or `average`).
Have added that, and also updated the overall documentation on multi-query to be as clear as possible.

2022-09-12 19:28 UTC, JorTurFer approved these changes

2022-09-12 19:29 UTC, merged