fix: 404 Microsoft link
kedacore/keda-docs pull request #958
Opened 2022-10-13 15:19 UTC by endersonmenezes

Fixing a 404 Microsoft Link

Signed-off-by: Enderson Menezes (Mr. Enderson) <endersonster@gmail.com>

The link [Old link](https://docs.microsoft.com/en-us/azure/devops/pipelines/agent/agent-pool-demands) does not working any more. I searched a new link: [New Link](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml)

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO)

2022-10-13 15:25 UTC, tomkerkhove requested changes
Thanks! Did you check if older versions have the same link?

Would you mind updating at least v2.9 as well please?

2022-10-13 17:14 UTC, endersonmenezes commented
@tomkerkhove I'll check, I didn't pay attention to that. Give me a few more hours =]

2022-10-14 07:40 UTC, tomkerkhove commented
No problem at all!

2022-10-14 07:41 UTC, tomkerkhove approved these changes
LGTM, thanks a ton!

2022-10-14 07:41 UTC, merged