Adds CouchDB scaler docs
kedacore/keda-docs pull request #967
Opened 2022-11-01 15:00 UTC by 26tanishabanik

Signed-off-by: 26tanishabanik <26tanishabanik@gmail.com>

_Provide a description of what has been changed_

 - Adds CouchDB scaler docs to v2.9

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO)

Relates to [kedacore/keda#3746](https://github.com/kedacore/keda/issues/3746)
Relates to https://github.com/kedacore/keda/pull/3804

2022-11-02 08:34 UTC, tomkerkhove approved these changes
LGTM, thank you!

2022-11-13 20:04 UTC, JorTurFer requested changes
Sorry for the slow response...
I can see in the code that there is another parameter named `connectionString` not documented here. We should also put in `Authentication Parameters` section all the parameter which can be got from authentication, I see in the code that `host`, `port` and `connectionString` are recovered too from there

2022-11-13 20:04 UTC, JorTurFer commented on content/docs/2.9/scalers/couchdb.md
> +    hostname: "test-release-svc-couchdb.couchdb-test-ns.svc.cluster.local"
This parameter in code is named `host`

2022-12-05 09:35 UTC, zroubalik commented on content/docs/2.9/scalers/couchdb.md
> +    metricName: "global-metric"
Please remove `metricName` property, we try to get rid of those from user config, since it is internal thing only. Thanks!

2022-12-05 09:35 UTC, zroubalik commented on content/docs/2.9/scalers/couchdb.md
> +- `metricName` - Name to assign to the metric. (Default: `s<X>-couchdb-<KEYSPACE>`, Optional, In case of `metricName` is specified, it will be used to generate the `metricName` like this: `s<X>-couch
remove pls

2022-12-05 09:57 UTC, 26tanishabanik commented on content/docs/2.9/scalers/couchdb.md
> +    hostname: "test-release-svc-couchdb.couchdb-test-ns.svc.cluster.local"
Sure, I will add it @JorTurFer

2022-12-08 10:03 UTC, zroubalik requested changes

2022-12-08 10:03 UTC, zroubalik commented on content/docs/2.9/scalers/couchdb.md
> +    hostname: "test-release-svc-couchdb.couchdb-test-ns.svc.cluster.local"
@26tanishabanik please fix this

2022-12-08 10:36 UTC, zroubalik approved these changes

2022-12-08 15:03 UTC, merged